### ISSUE TITLE
Add more options to the Grade Drop-down list

### ISSUE THREAD

**Issue by lwiere** [srobotta/moodle-tiny_cloze#16]
Hi,

first of all a big THANK YOU for this very handy and useful plugin.

We were discussing that having more %-values available in the grade drop-down list would be very useful. Between the lower values there are very small increments. However, once we reach the 50% grade, the next higher grade available in the list jumps to a full 100%.

![image](https://github.com/srobotta/moodle-tiny_cloze/assets/134299385/d5e32b7a-0e61-4881-ac29-bde40f4ac128)

The lack of smaller increments inspires users to first choose any value from the Cloze Editor drop-down, and then manipulate this value later on through the code view to get the value they actually need. 
Unfortunately, this is very dangerous since a single typo can break the whole question, which poses a huge risk (even more so if changing the grading for a question that has already been attempted in quizzes ;) ).
Also, if I manipulate in the code view and enter a value that isn't included in the drop-down, the next time I jump into the Cloze Editor these values default to "Incorrect" in the drop-down.

![image](https://github.com/srobotta/moodle-tiny_cloze/assets/134299385/e36f2484-0e75-41a1-8ba6-b2d0dde0ff07)

Any chance you can add smaller increments between the 50% and 100% mark?
Or are we missing something to make this work? We tried getting the 75% by using -25%, but then ended up with negative points.

Many thanks,
Lena

**Comment by srobotta** [comment]
Dear Lena,

Thank you for your request and your question. I have not a deep knowledge in exams and therefore don't exactly know where the scale with the percentage originates from. I will investigate further. Technically there is no problem to grade a almost correct answer with 75% or similar.
Meanwhile, you still can get to these percentage numbers. Create your questions with the tinyMCE and the help of this plugin. Before you finally save the question text, switch to the source view of the question text where you will see the HTML code. There you have the chance to edit the created cloze question string (as you would write it without having the plugin). At the specific answer you may change the percentage rate to any value you wish. Then save the question again.
What you should avoid then is to reedit the question with the plugin, because that would override your custom percentage rate. Editing the text without using the Cloze Question plugin does not change the cloze question string.

HTH before having a generic solution for your issue.
Stephan

**Comment by srobotta** [comment]
I have addressed the problem by changing the selection list and have an extra input field for the less common values. You might check out the main branch to see, if that fits your needs.

**Comment by srobotta** [comment]
I have drafted release 1.4 that contains this feature request. The release is available here at github as well as on moodle.org.
